language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install nose
  
  # this is for python's lxml
  - sudo apt-get install -y libdevel-cover-perl libxslt1-dev zlib1g-dev
  
  # for plugin-check_poller2livestatus
  - sudo apt-get install -y netcat-traditional
  
  # this is for plugin-check_rancid
  - sudo apt-get install -y python-svn
  
  # for plugin-check_libvirt_stats, a recent libvirt is available through backports
  # (before travis-ci gets updated with Ubuntu 14.04)
  - sudo apt-get install -y pkg-config
  - echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/icehouse main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes libvirt-dev libvirt-bin
  # libxml2 is broken on pypi
  - sudo apt-get install -y python-libxml2

script:
  - ./run_tests.sh

notifications:
  email: false

env:
  global:
    - secure: "QM1OdhXTAhSKrVeap7n6m9mmCdojz9CSxsvQebJ7qFCB+PK4pOhj2LoQWWM7nhJ+2ifkapDlRVFTBRgToUEvTlsUp8vXcbS8ke4hZrEzW6hytpcjbQSCk53j/uQ+OCQlza4OGpXpORY1Jkx3egDDRL9HXknDS1WTAefDKfWKf6E="
 
after_success:
  - sudo apt-get install osc
  - cat ~/.oscrc
  - echo $OSC_PASSWORD
  - (echo [https://api.opensuse.org] && echo user = ReAzem && echo password = $OSC_PASSWORD) > ~/.oscrc
  - ./tools/update_obs_packages.sh 
