language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install nose
  - sudo apt-get install -y libdevel-cover-perl libxslt1-dev zlib1g-dev
  # this is for python's lxml
  - sudo apt-get install -y netcat-traditional
  # for plugin-check_poller2livestatus
script:
  - ./run_tests.sh

notifications:
  email: false
