language: python
python:
  - "2.6"
#  - "2.7"
# removed temporarily
# rationale: "after_success" will be executed 2 times, that's not what we want (yet)

install:
  - pip install nose
  
  # this is for python's lxml
  - sudo apt-get install -y libdevel-cover-perl libxslt1-dev zlib1g-dev
  
  # for plugin-check_poller2livestatus
  - sudo apt-get install -y netcat-traditional
  
  # this is for plugin-check_rancid
  - sudo apt-get install -y python-svn
  
  # for plugin-check_libvirt_stats, a recent libvirt is available through backports
  # (before travis-ci gets updated with Ubuntu 14.04)
  - sudo apt-get install -y pkg-config
  - echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/icehouse main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes libvirt-dev libvirt-bin
  # libxml2 is broken on pypi
  - sudo apt-get install -y python-libxml2

script:
  - make tests

notifications:
  email: false

env:
  global:
    - secure: "BiqiWIRpj3mjTUKvz3CfsD0BTl1s730O/zcWBWnx4GK++K6/QrYckerAT3l8AI4ArYNspB1SCfl0/bZW3vPUeWZXxOQVN9YyloMyy7kOlonTMCfacgCR5ZXI5JorMyvmzt2RJnEmVLOnSejDo1MSHJfzoOWndORwFmcdVbfYXX0=" 
 
after_success:
  - sudo apt-get install osc devscripts
  - (echo [https://api.opensuse.org] && echo user = ReAzem && echo password = $OSC_PASSWORD) > ~/.oscrc
  - make deb && make obs
