language: python
python:
  - "2.6"
#  - "2.7"
# removed temporarily
# rationale: "after_success" will be executed 2 times, that's not what we want (yet)

install:
  - pip install nose
  
  # this is for python's lxml
  - sudo apt-get install -y libdevel-cover-perl libxslt1-dev zlib1g-dev
  
  # for plugin-check_poller2livestatus
  - sudo apt-get install -y netcat-traditional
  
  # this is for plugin-check_rancid
  - sudo apt-get install -y python-svn
  
  # for plugin-check_libvirt_stats, a recent libvirt is available through backports
  # (before travis-ci gets updated with Ubuntu 14.04)
  - sudo apt-get install -y pkg-config
  - echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/icehouse main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes libvirt-dev libvirt-bin
  # libxml2 is broken on pypi
  - sudo apt-get install -y python-libxml2

script:
#  - make tests
   - echo matthieu

notifications:
  email: false

env:
  global:
    - secure: "C0vVa517y9sjxSzSBryBwtXblMqdN/knZ2q07cMWbWat0Mb/qbIfOLcehC1TYXJaKqEdj8XycfOg07utjrd9V+JengHmQQ2AW52r4JIXBzOn9j4F9JNBe2hkYRNvpBGvn/UTqH3z7go3tRoKQJOfQ+jKij/WdS4zEhz3TL+RCY8=" 
 
after_success:
  - sudo apt-get install osc devscripts
  - (echo [general] && echo apiurl = https://api.opensuse.org && echo [https://api.opensuse.org] && echo user = ReAzem && echo pass = $OSC_PASSWORD) > ~/.oscrc
  - cat ~/.oscrc
  - make deb && make obs
